# 🛠 Архитектура базы данных проекта (SQL)

В данном разделе представлена структура базы данных для анализа факторов ДТП. 
Архитектура организована по принципу двухуровневого хранилища: **Staging** (буферная зона) и **Core** (аналитический слой).

---

## 🏗 1. Слой Staging (Сырые данные и справочники)

На данном этапе данные загружаются из внешних источников (API, JSON) в исходном виде. 
Это позволяет сохранить историю изменений и производить повторную обработку данных (ETL) без повторных обращений к внешним сервисам.
  
### 📍 Справочник городов (`cities_coords`)
Хранит базовую информацию о населенных пунктах, их географические координаты и административные коды (ОКАТО).

CREATE TABLE public.cities_coords (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NULL,
  region TEXT NULL,
  population BIGINT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  okato_region TEXT NULL,
  okato_city TEXT NULL,
  CONSTRAINT cities_coord_pkey PRIMARY KEY (id),
  CONSTRAINT unique_city_name UNIQUE (name, region)
);

### 🚨 Первичные данные ГИБДД (`gibdd_accidents_history_3_cities`)
Буферная таблица, объединяющая сведения о происшествиях, транспортных средствах и участниках. 
Содержит поля в формате JSONB для хранения неструктурированных списков нарушений и недостатков дороги.

CREATE TABLE public.gibdd_accidents_history_3_cities (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  kart_id BIGINT NULL,
  dtp_date DATE NULL,
  dtp_time TIME WITHOUT TIME ZONE NULL,
  district TEXT NULL,
  dtp_type TEXT NULL,
  pog_total INTEGER NULL,
  ran_total INTEGER NULL,
  vehicles_count INTEGER NULL,
  participants_count INTEGER NULL,
  city_name TEXT NULL,
  address_street TEXT NULL,
  address_house TEXT NULL,
  road_category TEXT NULL,
  weather TEXT NULL,
  road_condition TEXT NULL,
  light_condition TEXT NULL,
  latitude NUMERIC NULL,
  longitude NUMERIC NULL,
  road_faults JSONB NULL,
  v_id TEXT NULL,
  v_type TEXT NULL,
  v_marka TEXT NULL,
  v_model TEXT NULL,
  v_color TEXT NULL,
  v_year INTEGER NULL,
  v_ownership TEXT NULL,
  p_role TEXT NULL,
  p_gender TEXT NULL,
  p_experience INTEGER NULL,
  p_severity TEXT NULL,
  p_alcohol TEXT NULL,
  p_safety_belt TEXT NULL,
  p_violations JSONB NULL,
  p_additional_violations JSONB NULL,
  city_id BIGINT NULL,
  CONSTRAINT gibdd_accidents_history_3_cities_pkey PRIMARY KEY (id),
  CONSTRAINT gibdd_accidents_history_3_cities_city_id_fkey FOREIGN KEY (city_id) REFERENCES cities_coords (id)
);

CREATE INDEX IF NOT EXISTS idx_kart_id ON public.gibdd_accidents_history_3_cities (kart_id);
CREATE INDEX IF NOT EXISTS idx_dtp_date ON public.gibdd_accidents_history_3_cities (dtp_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_accident_participant ON public.gibdd_accidents_history_3_cities (kart_id, v_id, p_role, p_gender, p_experience);

### ☁️ История погоды (`weather_history_3_cities`)
Служит для сопоставления условий окружающей среды с моментами ДТП. Включает детальные метеоданные, такие как влажность, давление и тип осадков.

CREATE TABLE public.weather_history_3_cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  city TEXT NOT NULL,
  timestamp TIMESTAMP WITHOUT TIME ZONE NULL,
  temp REAL NULL,
  humidity REAL NULL,
  precipitation REAL NULL,
  weather_code SMALLINT NULL,
  weather_description TEXT NULL,
  wind_speed REAL NULL,
  pressure DOUBLE PRECISION NULL,
  snow_depth DOUBLE PRECISION NULL,
  rain DOUBLE PRECISION NULL,
  snowfall DOUBLE PRECISION NULL,
  apparent_temp DOUBLE PRECISION NULL,
  CONSTRAINT weather_history_3_cities_pkey PRIMARY KEY (id),
  CONSTRAINT unique_city_time UNIQUE (city, "timestamp"),
  CONSTRAINT weather_history_3_cities_city_fkey FOREIGN KEY (city) REFERENCES cities_coords (name)
);

## 💎 2. Аналитический слой (Core Layer)

В данном слое данные проходят процесс **ETL** (очистка, нормализация, дедупликация). Структура оптимизирована для выполнения аналитических запросов и построения визуализаций.

### 📊 Таблицы фактов и измерений


| Таблица | Описание |
| :--- | :--- |
| **2.1. accidents** | **Центральная таблица фактов.** Хранит агрегированную информацию о ДТП, приведенное к UTC время и количество пострадавших. |
| **2.2. cities** | Справочник городов с актуальным населением и географическими центрами. |
| **2.3. location** | Детальные координаты и привязка каждого инцидента к району и городу. |
| **2.4. vehicles** | Информация о транспортных средствах: марки, возрастные группы и формы собственности. |
| **2.5. participants** | Профили участников: опыт вождения, использование систем безопасности и детальные категории нарушений. |
| **2.6. road** | Характеристики дорожной инфраструктуры: знаки, разметка и выявленные недостатки. |

---

### 📂 SQL-структура таблиц Core-слоя

-- 2.1. Основная таблица происшествий
  
CREATE TABLE public.accidents (
  kart_id INTEGER NOT NULL,
  dtp_type_group TEXT NULL,
  pog_total SMALLINT NULL,
  ran_total SMALLINT NULL,
  vehicles_count SMALLINT NULL,
  participants_count SMALLINT NULL,
  dtp_hour_utc TIMESTAMP WITHOUT TIME ZONE NULL,
  weather_from_gibdd TEXT NULL,
  city_name TEXT NULL,
  CONSTRAINT accidents_pkey PRIMARY KEY (kart_id)
);

CREATE INDEX IF NOT EXISTS idx_accidents_weather_time ON public.accidents (dtp_hour_utc);

-- 2.2. Справочник городов (очищенный)

CREATE TABLE public.cities (
  id INTEGER NOT NULL,
  city_name TEXT NULL,
  region TEXT NULL,
  population INTEGER NULL,
  latitude REAL NULL,
  longitude REAL NULL,
  okato_region TEXT NULL,
  okato_city TEXT NULL,
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT unique_city UNIQUE (city_name)
);

-- 2.3. Геолокация ДТП

CREATE TABLE public.location (
  kart_id INTEGER NULL,
  district TEXT NULL,
  city_name TEXT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  CONSTRAINT fk_location_city FOREIGN KEY (city_name) REFERENCES cities (city_name),
  CONSTRAINT location_kart_id_fkey FOREIGN KEY (kart_id) REFERENCES accidents (kart_id)
);

-- 2.4. Транспортные средства

CREATE TABLE public.vehicles (
  kart_id INTEGER NOT NULL,
  v_id TEXT NOT NULL,
  v_marka TEXT NULL,
  v_model TEXT NULL,
  v_ownership_origin TEXT NULL,
  v_ownership_detail TEXT NULL,
  vehicle_category TEXT NULL,
  v_color_clean TEXT NULL,
  vehicle_age_group TEXT NULL,
  CONSTRAINT vehicles_pkey PRIMARY KEY (kart_id, v_id),
  CONSTRAINT vehicles_kart_id_fkey FOREIGN KEY (kart_id) REFERENCES accidents (kart_id)
);

-- 2.5. Участники ДТП

CREATE TABLE public.participants (
  kart_id INTEGER NULL,
  v_id TEXT NULL,
  p_role TEXT NULL,
  p_gender TEXT NULL,
  experience_group TEXT NULL,
  p_severity_clean TEXT NULL,
  p_alcohol_clean TEXT NULL,
  p_safety_belt BOOLEAN NULL,
  violation_consolidated TEXT NULL,
  v_driver_status_total BOOLEAN NULL,
  v_driver_docs_total BOOLEAN NULL,
  v_driver_safety_total BOOLEAN NULL,
  v_driver_escape_total BOOLEAN NULL,
  v_driver_speed_total BOOLEAN NULL,
  v_driver_tech_total BOOLEAN NULL,
  v_driver_overtaking_total BOOLEAN NULL,
  v_driver_maneuver_total BOOLEAN NULL,
  v_driver_priority_total BOOLEAN NULL,
  v_driver_distance_total BOOLEAN NULL,
  v_driver_heavy_cargo_total BOOLEAN NULL,
  v_driver_dangerous_total BOOLEAN NULL,
  v_driver_other_total BOOLEAN NULL,
  v_pedestrian_rules_total BOOLEAN NULL,
  v_micromobility_rules_total BOOLEAN NULL,
  v_police_emergency_total BOOLEAN NULL,
  v_no_violations_total BOOLEAN NULL,
  CONSTRAINT participants_kart_id_v_id_fkey FOREIGN KEY (kart_id, v_id) REFERENCES vehicles (kart_id, v_id)
);

-- 2.6. Дорожные условия

CREATE TABLE public.road (
  kart_id INTEGER NULL,
  road_condition_group TEXT NULL,
  road_marking BOOLEAN NULL,
  road_signs BOOLEAN NULL,
  street_lighting BOOLEAN NULL,
  pavement_defects BOOLEAN NULL,
  winter_conditions BOOLEAN NULL,
  traffic_light BOOLEAN NULL,
  drainage_system BOOLEAN NULL,
  road_narrowing BOOLEAN NULL,
  bus_stop_elements BOOLEAN NULL,
  road_works_zone_tsod BOOLEAN NULL,
  faults_consolidated TEXT NULL,
  light_condition TEXT NULL,
  road_category TEXT NULL,
  CONSTRAINT road_kart_id_fkey FOREIGN KEY (kart_id) REFERENCES accidents (kart_id)
);
